Network:
  epochs: 300
  batch_size: 16
  n_steps: 20
  dataset: "CIFAR10DVS"
  data_path: "../../datasets/cifar10_dvs"
  # data_path: "../../../../datasets/cifar10_dvs"
  log_path: "logs/cifar10_dvs"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0002
  weight_decay: 0.002
  loss: "count+"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 10
  desired_count: 10
  undesired_count: 1
  tau_m: 8
  tau_s: 4.5
  tau_grad: 4

Layers:
  conv_1:
    type: "conv"   # 48*48
    in_channels: 2
    out_channels: 128
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_1:
    type: "pooling"
    kernel_size: 2
  
  dropout_1:
    type: "dropout"
    p: 0.1

  conv_2:
    type: "conv" # 24*24
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_3:
    type: "conv" # 24*24
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  pooling_2:
    type: "pooling"
    kernel_size: 2

  dropout_2:
    type: "dropout"
    p: 0.1

  conv_4:
    type: "conv"  # 12*12
    in_channels: 256
    out_channels: 256
    kernel_size: 3
    padding: 1
    threshold: 1

  conv_5:
    type: "conv" # 12*12
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_3:
    type: "pooling"
    kernel_size: 2

  dropout_3:
    type: "dropout"
    p: 0.1
  
  conv_6:
    type: "conv" # 6*6
    in_channels: 512
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  conv_7:
    type: "conv" # 6*6
    in_channels: 512
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  conv_8:
    type: "conv" # 6*6
    in_channels: 512
    out_channels: 512
    kernel_size: 3
    padding: 1
    threshold: 1
  
  pooling_4:
    type: "pooling"
    kernel_size: 2

  dropout_4:
    type: "dropout"
    p: 0.1

  FC_1:
    type: "linear"
    n_inputs: 4608
    n_outputs: 1024
    threshold: 1

  dropout_5:
    type: "dropout"
    p: 0.1

  FC_2:
    type: "linear"
    n_inputs: 1024
    n_outputs: 1024
    threshold: 1
  
  dropout_6:
    type: "dropout"
    p: 0.1

  output:
    type: "linear"
    n_inputs: 1024
    n_outputs: 10
    threshold: 1