Network:
  epochs: 100
  batch_size: 50
  sample_rate: 16000
  n_steps: 101
  dataset: "SpeechCommand"
  data_path: "../../datasets/speech_command"
  # data_path: "../../../../datasets/speech_command"
  log_path: "logs/speech_command"
  backend: "cuda"
  optimizer: "AdamW"
  lr: 0.0005
  weight_decay: 0.05
  weight_decay_norm: 0.001
  avg_spike_init: 0.6
  loss: "count+"
  gradient_type: "exponential"
  pooling_type: "adjusted_avg"
  n_class: 12
  desired_count: 5
  undesired_count: 1
  tau_m: 5
  tau_s: 3
  tau_grad: 2.5

Layers:
  FC_1:
    type: "linear"
    n_inputs: 40
    n_outputs: 128
    threshold: 1
  
  FC_2:
    type: "linear"
    n_inputs: 128
    n_outputs: 32
    threshold: 1

  output:
    type: "linear"
    n_inputs: 32
    n_outputs: 12
    threshold: 1
